### ISSUE TITLE
i think u can "rot in a hole and die".

### ISSUE THREAD

**Issue by srgantmoomoo** [Supergamer5465/Anti-ImpHack#69]
is this a joke?... am i getting baited? or is this a fork or smthn? "It is completely original and no skidding was done. Skidders can rot in a hole and die!"

https://github.com/Supergamer5465/Anti-ImpHack/blob/master/src/main/java/mod/imphack/module/modules/combat/CrystalConfigHelper.java

i know damn well that is skidded... cause i wrote it. as well as like a lot of other shit lol. ur crystal aura is skidded too, as im now looking at it. and im sure everything else here is also lol.

**Comment by Supergamer5465** [comment]
I didn’t make ca. Would you like us to change it?

**Comment by Droid-D3V** [comment]
Supergamer5465, why? This is highly skidded, I see Phobos, Postman [as stated above], and a lot more, so please fix this, also, if you could, please fix your concrete bot, it doesn't work for me on 5b5t, thanks -Droid_D3V, Copinqqq

**Comment by Droid-D3V** [comment]
I also see that you changed the README.md, lol

**Comment by Errorcrafter** [comment]
don't be obtuse, this is obviously supposed to be one of those "multi-clients" everyone's talking about

**Comment by FlufferyGR** [comment]
Im sorry srgant, i didnt make it at all, i just edited the readme, ill check it tho

**Comment by Supergamer5465** [comment]
@Errorcrafter wtf is a multi client

**Comment by FlufferyGR** [comment]
Either a client mixxed with alot of others pr one u ise as a side 1

**Comment by Supergamer5465** [comment]
@Droid-D3V I’ll try to fix some of the skidded prts and also concretebot

**Comment by srgantmoomoo** [comment]
> I didn’t make ca. Would you like us to change it?

I don't care. I would at least appreciate credit. And I'm sure the other devs who were skidded would too. But once again I don't really care, it's not my project. At least don't condemn skidding when a vast majority of your code (or your contributors code) is skidded.

**Comment by master7720** [comment]
xD

**Comment by Supergamer5465** [comment]
@master7720 the tard who added garbage to the readme no longer has access to the repo. Also, the base client is not skidded in the least. I apologize on imphack dev team’s behalf for any skidded modules that were not given proper credit. We will be fixing this soon. Thank you, goodbye.

**Comment by master7720** [comment]
Whats wrong with the readme?

**Comment by srgantmoomoo** [comment]
I love how my comments r still there too

**Comment by notperry1234567890** [comment]
> I love how my comments r still there too

hi srgant

**Comment by Supergamer5465** [comment]
this is what y'all wanted? https://github.com/Supergamer5465/Anti-ImpHack/commit/137184ae101fb4f8c53c2018f4ebcfed28161771#diff-6913acfcf30bc3b9ced76f77d41b377f35b4d20ec488b9231c1f8a35f73e3814R10

**Comment by Errorcrafter** [comment]
actually that doesnt resolve the issue at all, according to the title you need to "rot in a hole and die" to fix it

**Comment by Supergamer5465** [comment]
fair enough

**Comment by srgantmoomoo** [comment]
i'm not even gonna comment on this anymore lol... changing some random shit around, making the code worse just to make it different... doesn't do anything! i really don't care if u credit me or not... i was just pointing out your hipocracy. i don't care what u do, its your project. if u want to credit ppl than do that, if not, than that's on u. also i don't need people asking me what is skidded and what to fix, ya'll are the ones who made the damn thing, im not gonna waste my time looking for your skidded code. do as u wish, i don't care.

**Comment by srgantmoomoo** [comment]
> > I love how my comments r still there too
> 
> hi srgant

hi perry

**Comment by srgantmoomoo** [comment]
> Im sorry srgant, i didnt make it at all, i just edited the readme, ill check it tho

hi fluffery. idc lol, from the looks of it, the skidded code is mostly from pr's.

**Comment by FlufferyGR** [comment]
Its all prs

**Comment by Supergamer5465** [comment]
@srgantmoomoo thats my fucking auto-format read the comment

**Comment by srgantmoomoo** [comment]
ur auto format is a little funky
